# Site settings
author: Willis Aybar
title: My Flatiron Experience
header-img: img/home-bg.png
email: willisaybar@gmail.com
copyright_name: Willis Aybar
description: > # this means to ignore newlines until "baseurl:"
  The Process Is Everything
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: WillisAybar
github_username:  willisaybar

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
